#!/usr/bin/env python3

# (C) 2020 Aalok S.

from subprocess import run
from pathlib import Path
import sys

conf = Path('~/.config/loopback.switch') # stores current state.
                                         # 0 --> loopback disabled
                                         # 1 --> loopback enabled
conf = conf.expanduser()
if not conf.exists():
    conf.touch()
    conf.write_text('0')

inverse = {'1':'0', '0':'1'}

b = sys.argv[1] if len(sys.argv) > 1 else inverse[conf.read_text()]
conf.write_text(b)

enable = 'pactl load-module module-loopback latency_msec=1'
disable = 'pactl unload-module module-loopback'
if b == '1':
    run(enable, shell=True)
else:
    run(disable, shell=True)
